### PR TITLE
WIP: Add xcode 11 support

### PR DESCRIPTION
**Pull request by xvilo**

### CODE REVIEW

**Comment by xvilo** [comment]
[WebViewScreenSaver.saver.zip](https://github.com/liquidx/webviewscreensaver/files/3772824/WebViewScreenSaver.saver.zip)

It doesnt seem to work

**Comment by elalemanyo** [comment]
`CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'net.liquidx.WebViewScreenSaver'`

**Comment by elalemanyo** [comment]
Can we try to change `NSJSONReadingMutableContainers` to `NSJSONReadingAllowFragments`
here https://github.com/liquidx/webviewscreensaver/blob/master/WebViewScreenSaver/WVSSAddressListFetcher.m#L60

https://developer.apple.com/documentation/foundation/nsjsonreadingoptions?language=objc

https://github.com/Mantle/Mantle/issues/484

**Comment by rickvandermeij-aanzee** [comment]
Any updates?

**Comment by xvilo** [comment]
Nope not yet, work is crazy as hell lately ;)

**Pull request closed without merging**
